### ISSUE TITLE
Typescript cannot have double exports in same file

### ISSUE THREAD

**Issue by mmestas** [ungoldman/format-duration#19]
I got an error because there were two exports in your format-duration.d.ts file.

Here's what I updated and the ts compiler is happy now.

`
declare namespace formatDuration {
   interface FormatDurationOptions {
      /**
       * Adds leading zero to the formatted string.
       */
      leading?: boolean
      ms?: boolean
    }
}

/**
 * Convert a number in milliseconds to a standard duration string.
 *
 * @param {number} ms The number to format.
 * @param {object} options - Formatting options
 * @returns {string} The formatted duration string.
 */
declare function formatDuration (ms: number, options?: formatDuration.FormatDurationOptions): string

export = formatDuration
`

**Comment by ungoldman** [comment]
Export of type definitions was requested and implemented by @sebinemeth in https://github.com/ungoldman/format-duration/pull/15

@sebinemeth would you be able to contribute a fix to this?

**Comment by ungoldman** [comment]
Alternately @mmestas if you're able to open a pull request with the appropriate changes I'll be happy to review that. It's a bit difficult to review the code you posted above without a diff. Also the markdown syntax you're using didn't work, I suggest using the [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) syntax.

**Comment by sebinemeth** [comment]
Hi folks,
I created a PR: https://github.com/ungoldman/format-duration/pull/20. The suggested change makes sense, although I did not have issues with the multiple exports. @ungoldman please test it thoroughly before releasing it.

**Comment by ungoldman** [comment]
@sebinemeth I am not a typescript user, I am providing type definitions as a courtesy for this open source project because of frequent requests. I would ask that you and @mmestas test to make sure these changes satisfy both your use cases, and I will merge and deploy if you're both happy with it.

**Comment by mmestas** [comment]
Just seeing this now.  The diff looks good.

**Comment by ungoldman** [comment]
Should be resolved by #20, let me know if there are any more issues.
