### ISSUE TITLE
This package should be published pre-compiled

### ISSUE THREAD

**Issue by boonpflug** [ungoldman/format-duration#2]
As of now this is not building in minified builds/

**Comment by ungoldman** [comment]
Hi @boonpflug! What is the compilation target you are trying to use this for? This module was designed for use in a node 8+ environment, but with something like browserify, babel, or webpack, it should be compilable for browser environments like most other node modules out there.

**Comment by SinZ163** [comment]
The minifer that webpack uses doesn't understand ES6 syntax so it falls over on pretty much every line in this library (string templates, array / object destructuring, etc) and create-react-app tells developers to go to libraries (like this) and tell them to ship ES5 compatible builds

**Comment by henrikbjorn** [comment]
Normally with Webpack one would exclude `/node_modules/` from `babel-loader`. I am running into the same problem.

**Comment by ungoldman** [comment]
Hi folks, I understand the concern.

I am open to converting this library to ES5 to help with this issue.

I'd rather not introduce a build step to avoid over-complicating maintenance of a very small module.

**Comment by ungoldman** [comment]
This module was converted to ES5 in https://github.com/ungoldman/format-duration/commit/86c791e12ec710feb365260a1fd450ad1cc1b6f0.

The change was released in [`v1.2.0`](https://github.com/ungoldman/format-duration/releases/tag/v1.2.0).

🖖
